# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-toml
          - id: check-yaml
            args:
                - --unsafe
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.7.0
      hooks:
          - id: pyupgrade
            args:
                - --py3-plus
                - --keep-runtime-typing
    - repo: local
      hooks:
          - id: run_tests
            language: script
            name: Run Tests
            entry: ./run_tests.sh
            stage: [commit]
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.4.1
      hooks:
          - id: mypy
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.0.280
      hooks:
          - id: ruff
            args:
                - --fix
                - --exit-non-zero-on-fix

ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
