name: test

on:
    # Trigger the workflow on push or pull request on main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        # Run cron job every month, https://crontab.guru/every-month
        - cron: "0 0 1 * *"

jobs:
    # This job tests that the CC works
    test-cc:
        runs-on: {% raw %}${{ matrix.os }}{% endraw %}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.7", "3.9", "3.10", "3.11"]
        steps:
            - uses: actions/checkout@v3
            # Setup
            - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
              uses: actions/setup-python@v4
              with:
                  python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
            # Run tests
            - name: Pytest tests
              run: |
                  pytest tests/
